services:
  web:
    build:
      context: .
    expose:
      - 8000
    volumes:
      - uploads:/app/uploads
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - uploads:/app/uploads

volumes:
  uploads:
